/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as ImplantacoesRouteImport } from './routes/implantacoes'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as RecargasRouteImport } from './routes/recargas'
import { Route as RetiradasRouteImport } from './routes/retiradas'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantacoesRoute = ImplantacoesRouteImport.update({
  id: '/implantacoes',
  path: '/implantacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const RecargasRoute = RecargasRouteImport.update({
  id: '/recargas',
  path: '/recargas',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiradasRoute = RetiradasRouteImport.update({
  id: '/retiradas',
  path: '/retiradas',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/implantacoes': typeof ImplantacoesRoute
  '/indicadores': typeof IndicadoresRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pendencias': typeof PendenciasRoute
  '/recargas': typeof RecargasRoute
  '/retiradas': typeof RetiradasRoute
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/implantacoes': typeof ImplantacoesRoute
  '/indicadores': typeof IndicadoresRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pendencias': typeof PendenciasRoute
  '/recargas': typeof RecargasRoute
  '/retiradas': typeof RetiradasRoute
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/documentos': typeof DocumentosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/implantacoes': typeof ImplantacoesRoute
  '/indicadores': typeof IndicadoresRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pendencias': typeof PendenciasRoute
  '/recargas': typeof RecargasRoute
  '/retiradas': typeof RetiradasRoute
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/documentos'
    | '/equipamentos'
    | '/implantacoes'
    | '/indicadores'
    | '/pacientes'
    | '/pendencias'
    | '/recargas'
    | '/retiradas'
    | '/pacientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/documentos'
    | '/equipamentos'
    | '/implantacoes'
    | '/indicadores'
    | '/pacientes'
    | '/pendencias'
    | '/recargas'
    | '/retiradas'
    | '/pacientes/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/documentos'
    | '/equipamentos'
    | '/implantacoes'
    | '/indicadores'
    | '/pacientes'
    | '/pendencias'
    | '/recargas'
    | '/retiradas'
    | '/pacientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  DocumentosRoute: typeof DocumentosRoute
  EquipamentosRoute: typeof EquipamentosRoute
  ImplantacoesRoute: typeof ImplantacoesRoute
  IndicadoresRoute: typeof IndicadoresRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  PendenciasRoute: typeof PendenciasRoute
  RecargasRoute: typeof RecargasRoute
  RetiradasRoute: typeof RetiradasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantacoes': {
      id: '/implantacoes'
      path: '/implantacoes'
      fullPath: '/implantacoes'
      preLoaderRoute: typeof ImplantacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recargas': {
      id: '/recargas'
      path: '/recargas'
      fullPath: '/recargas'
      preLoaderRoute: typeof RecargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiradas': {
      id: '/retiradas'
      path: '/retiradas'
      fullPath: '/retiradas'
      preLoaderRoute: typeof RetiradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof PacientesRoute
    }
  }
}

interface PacientesRouteChildren {
  PacientesIdRoute: typeof PacientesIdRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesIdRoute: PacientesIdRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  DocumentosRoute: DocumentosRoute,
  EquipamentosRoute: EquipamentosRoute,
  ImplantacoesRoute: ImplantacoesRoute,
  IndicadoresRoute: IndicadoresRoute,
  PacientesRoute: PacientesRouteWithChildren,
  PendenciasRoute: PendenciasRoute,
  RecargasRoute: RecargasRoute,
  RetiradasRoute: RetiradasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
