/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ImplantacoesRouteImport } from './routes/implantacoes'
import { Route as RecargasRouteImport } from './routes/recargas'
import { Route as RetiradasRouteImport } from './routes/retiradas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantacoesRoute = ImplantacoesRouteImport.update({
  id: '/implantacoes',
  path: '/implantacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecargasRoute = RecargasRouteImport.update({
  id: '/recargas',
  path: '/recargas',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiradasRoute = RetiradasRouteImport.update({
  id: '/retiradas',
  path: '/retiradas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/implantacoes': typeof ImplantacoesRoute
  '/recargas': typeof RecargasRoute
  '/retiradas': typeof RetiradasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/implantacoes': typeof ImplantacoesRoute
  '/recargas': typeof RecargasRoute
  '/retiradas': typeof RetiradasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/implantacoes': typeof ImplantacoesRoute
  '/recargas': typeof RecargasRoute
  '/retiradas': typeof RetiradasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/implantacoes' | '/recargas' | '/retiradas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/implantacoes' | '/recargas' | '/retiradas'
  id: '__root__' | '/' | '/auth' | '/implantacoes' | '/recargas' | '/retiradas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ImplantacoesRoute: typeof ImplantacoesRoute
  RecargasRoute: typeof RecargasRoute
  RetiradasRoute: typeof RetiradasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implantacoes': {
      id: '/implantacoes'
      path: '/implantacoes'
      fullPath: '/implantacoes'
      preLoaderRoute: typeof ImplantacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recargas': {
      id: '/recargas'
      path: '/recargas'
      fullPath: '/recargas'
      preLoaderRoute: typeof RecargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiradas': {
      id: '/retiradas'
      path: '/retiradas'
      fullPath: '/retiradas'
      preLoaderRoute: typeof RetiradasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ImplantacoesRoute: ImplantacoesRoute,
  RecargasRoute: RecargasRoute,
  RetiradasRoute: RetiradasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
